# Generated by Django 5.2.1 on 2025-06-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pieza',
            options={'ordering': ['id']},
        ),
    ]
