# Generated by Django 5.2.1 on 2025-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pieza_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre común'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='revision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Revisión'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
