# Generated by Django 5.2.1 on 2025-06-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pieza_nombre_comun_pieza_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='materiales',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='pieza',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='tecnica',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='filiacion_cultural',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='exposiciones',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='pieza',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='materiales',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='tecnica',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Coleccion',
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.DeleteModel(
            name='Cultura',
        ),
        migrations.DeleteModel(
            name='Exposicion',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Tecnica',
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
    ]
