"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv


BASE_DIR    = Path(__file__).resolve().parent.parent   # …/CatalogoMAPA/backend
PROJECT_DIR = BASE_DIR.parent                          # …/CatalogoMAPA
load_dotenv(PROJECT_DIR / '.env')

MEDIA_URL  = '/imagenes/'
MEDIA_ROOT = PROJECT_DIR / 'imagenes'   # <— ahora Django subirá *dentro* de la carpeta raíz/imagenes
MEDIA_UPLOAD_SUBDIR = 'uploads'  # subcarpeta para cargas manuales

# Cloudinary: si está configurado, las URLs de imagen apuntan a Cloudinary en vez de MEDIA_URL local.
# Ejemplo: "https://res.cloudinary.com/tu-cloud-name/image/upload/mapa/"
CLOUDINARY_BASE_URL = os.environ.get('CLOUDINARY_BASE_URL', '')

# usa la URL base + credenciales
bolt_url = os.getenv('NEO4J_URI', 'bolt://neo4j:7687')
user    = os.getenv('NEO4J_USER', 'neo4j')
pwd     = os.getenv('NEO4J_PASSWORD', 'neo4j')
print(f"[SETTINGS] NEO4J_URI scheme: {bolt_url.split('://')[0] if '://' in bolt_url else 'NONE'}")
# inyecta usuario y contraseña en la URL
if '://' in bolt_url and '@' not in bolt_url:
    scheme, rest = bolt_url.split('://', 1)
    bolt_url = f"{scheme}://{user}:{pwd}@{rest}"
NEO4J_BOLT_URL = bolt_url

try:
    from neomodel import config as neomodel_config
    neomodel_config.DATABASE_URL = bolt_url
    print("[SETTINGS] neomodel config set OK")
except Exception as e:
    print(f"[SETTINGS] neomodel config error: {e}")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-me")

DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    # apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # REST framework y filtro
    'rest_framework',
    'django_filters',

    'rest_framework_simplejwt',      # ← JWT
    'accounts', # la app para administrar las cuentas de usuarios

    # la aplicación que contiene los modelos
    'api.apps.ApiConfig',

    "corsheaders",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:8080,http://localhost:5173"
).split(",")
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Solo en desarrollo

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # opcional: paginación, permiso por defecto, etc.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Usuario personalzido
AUTH_USER_MODEL = 'accounts.Usuario'

# Email y URLs externas
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@inventariomapa.local")
FRONTEND_BASE_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")